apiVersion: v1
kind: Service
metadata:
  name: {{ include "cv-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ include "cv-chart.name" . }}