apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cv
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: kaspersvend/cv
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-digest: "true"  # Tracks the digest for latest updates
    argocd-image-updater.argoproj.io/image-tag-force-update: "true"
spec:
  project: default
  source:
    repoURL: 'https://github.com/KasperSvendsen/helm-deployments'
    targetRevision: main
    path: cv-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: cv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true