# values.yaml

image:
  repository: kaspersvend/cv
  tag: "latest"  # Argo CD Image Updater will dynamically update this tag.

service:
  port: 80

ingress:
  enabled: true
  host: kaspersvendsen.dk
  tlsSecret: kaspersvendsen-cert