image:
  repository: kaspersvend/cv
  pullPolicy: Always
  tag: "v33.0.0"  # Updated to use the specific version instead of "latest"

service:
  type: ClusterIP             # Keep as ClusterIP unless you want LoadBalancer
  port: 80                    # The service will listen on port 80

ingress:
  enabled: true               # Enable ingress for the CV app
  host: kaspersvendsen.dk      # Your domain for the CV app
  tlsSecret: kaspersvendsen-cert  # The TLS secret name for HTTPS