image:
  repository: kaspersvend/cv
  tag: "v0.1.0"  # Initially set to a specific version or "latest"
  pullPolicy: Always

service:
  port: 80

ingress:
  enabled: true
  host: kaspersvendsen.dk
  tlsSecret: kaspersvendsen-cert