image:
  repository: kaspersvend/cv
  tag: "{{ .Values.image.tag }}"  # Use Helm templating to pass the version dynamically.
  pullPolicy: Always

service:
  port: 80

ingress:
  enabled: true
  host: kaspersvendsen.dk
  tlsSecret: kaspersvendsen-cert